/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAktualityRouteImport } from './routes/_authenticated/aktuality'
import { Route as AuthenticatedNastenkaRouteImport } from './routes/_authenticated/nastenka'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedSkladRouteImport } from './routes/_authenticated/sklad'
import { Route as AuthenticatedSpravyRouteImport } from './routes/_authenticated/spravy'
import { Route as AuthenticatedSusediaRouteImport } from './routes/_authenticated/susedia'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSkladItemIdRouteImport } from './routes/_authenticated/sklad.$itemId'
import { Route as AuthenticatedWarehouseItemIdRouteImport } from './routes/_authenticated/warehouse.$itemId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAktualityRoute = AuthenticatedAktualityRouteImport.update({
  id: '/aktuality',
  path: '/aktuality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNastenkaRoute = AuthenticatedNastenkaRouteImport.update({
  id: '/nastenka',
  path: '/nastenka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkladRoute = AuthenticatedSkladRouteImport.update({
  id: '/sklad',
  path: '/sklad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpravyRoute = AuthenticatedSpravyRouteImport.update({
  id: '/spravy',
  path: '/spravy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSusediaRoute = AuthenticatedSusediaRouteImport.update({
  id: '/susedia',
  path: '/susedia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSkladItemIdRoute =
  AuthenticatedSkladItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedSkladRoute,
  } as any)
const AuthenticatedWarehouseItemIdRoute =
  AuthenticatedWarehouseItemIdRouteImport.update({
    id: '/warehouse/$itemId',
    path: '/warehouse/$itemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/aktuality': typeof AuthenticatedAktualityRoute
  '/nastenka': typeof AuthenticatedNastenkaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/sklad': typeof AuthenticatedSkladRouteWithChildren
  '/spravy': typeof AuthenticatedSpravyRoute
  '/susedia': typeof AuthenticatedSusediaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sklad/$itemId': typeof AuthenticatedSkladItemIdRoute
  '/warehouse/$itemId': typeof AuthenticatedWarehouseItemIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/aktuality': typeof AuthenticatedAktualityRoute
  '/nastenka': typeof AuthenticatedNastenkaRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/sklad': typeof AuthenticatedSkladRouteWithChildren
  '/spravy': typeof AuthenticatedSpravyRoute
  '/susedia': typeof AuthenticatedSusediaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/sklad/$itemId': typeof AuthenticatedSkladItemIdRoute
  '/warehouse/$itemId': typeof AuthenticatedWarehouseItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/aktuality': typeof AuthenticatedAktualityRoute
  '/_authenticated/nastenka': typeof AuthenticatedNastenkaRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/sklad': typeof AuthenticatedSkladRouteWithChildren
  '/_authenticated/spravy': typeof AuthenticatedSpravyRoute
  '/_authenticated/susedia': typeof AuthenticatedSusediaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/sklad/$itemId': typeof AuthenticatedSkladItemIdRoute
  '/_authenticated/warehouse/$itemId': typeof AuthenticatedWarehouseItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/aktuality'
    | '/nastenka'
    | '/profil'
    | '/sklad'
    | '/spravy'
    | '/susedia'
    | '/auth/callback'
    | '/sklad/$itemId'
    | '/warehouse/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/aktuality'
    | '/nastenka'
    | '/profil'
    | '/sklad'
    | '/spravy'
    | '/susedia'
    | '/auth/callback'
    | '/'
    | '/sklad/$itemId'
    | '/warehouse/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/aktuality'
    | '/_authenticated/nastenka'
    | '/_authenticated/profil'
    | '/_authenticated/sklad'
    | '/_authenticated/spravy'
    | '/_authenticated/susedia'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/sklad/$itemId'
    | '/_authenticated/warehouse/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aktuality': {
      id: '/_authenticated/aktuality'
      path: '/aktuality'
      fullPath: '/aktuality'
      preLoaderRoute: typeof AuthenticatedAktualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nastenka': {
      id: '/_authenticated/nastenka'
      path: '/nastenka'
      fullPath: '/nastenka'
      preLoaderRoute: typeof AuthenticatedNastenkaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sklad': {
      id: '/_authenticated/sklad'
      path: '/sklad'
      fullPath: '/sklad'
      preLoaderRoute: typeof AuthenticatedSkladRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spravy': {
      id: '/_authenticated/spravy'
      path: '/spravy'
      fullPath: '/spravy'
      preLoaderRoute: typeof AuthenticatedSpravyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/susedia': {
      id: '/_authenticated/susedia'
      path: '/susedia'
      fullPath: '/susedia'
      preLoaderRoute: typeof AuthenticatedSusediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/sklad/$itemId': {
      id: '/_authenticated/sklad/$itemId'
      path: '/$itemId'
      fullPath: '/sklad/$itemId'
      preLoaderRoute: typeof AuthenticatedSkladItemIdRouteImport
      parentRoute: typeof AuthenticatedSkladRoute
    }
    '/_authenticated/warehouse/$itemId': {
      id: '/_authenticated/warehouse/$itemId'
      path: '/warehouse/$itemId'
      fullPath: '/warehouse/$itemId'
      preLoaderRoute: typeof AuthenticatedWarehouseItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSkladRouteChildren {
  AuthenticatedSkladItemIdRoute: typeof AuthenticatedSkladItemIdRoute
}

const AuthenticatedSkladRouteChildren: AuthenticatedSkladRouteChildren = {
  AuthenticatedSkladItemIdRoute: AuthenticatedSkladItemIdRoute,
}

const AuthenticatedSkladRouteWithChildren =
  AuthenticatedSkladRoute._addFileChildren(AuthenticatedSkladRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAktualityRoute: typeof AuthenticatedAktualityRoute
  AuthenticatedNastenkaRoute: typeof AuthenticatedNastenkaRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSkladRoute: typeof AuthenticatedSkladRouteWithChildren
  AuthenticatedSpravyRoute: typeof AuthenticatedSpravyRoute
  AuthenticatedSusediaRoute: typeof AuthenticatedSusediaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWarehouseItemIdRoute: typeof AuthenticatedWarehouseItemIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAktualityRoute: AuthenticatedAktualityRoute,
  AuthenticatedNastenkaRoute: AuthenticatedNastenkaRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSkladRoute: AuthenticatedSkladRouteWithChildren,
  AuthenticatedSpravyRoute: AuthenticatedSpravyRoute,
  AuthenticatedSusediaRoute: AuthenticatedSusediaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWarehouseItemIdRoute: AuthenticatedWarehouseItemIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
